name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Настройка на Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Инсталиране на зависимости
        run: npm ci

      - name: Build на React проекта
        run: npm run build -- silent

      - name: Публикуване на билда в deploy бранч
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Променено от build на dist
          branch: deploy
